### PR TITLE
Fix typescript rearrangement

### PR DESCRIPTION
**Pull request by davidanthoff**
This should fix the issue that the rearrangement of the typescript files broke the plotting stuff. I actually think it also broke a number of other things :)

This PR ends up being quite large because I did a whole bunch of things:
- split more things out into their own files
- only use classes where we need to, for now it seems easier to just stick with globals in modules, we can still change that later
- I introduced a general pattern how new features can live in their own file

My gut sense is that we can merge this soonish, but then we need to make sure we actually test all the features we have with the new version to make sure we 1) fixed the things that were broken and 2) I didn't introduce new bugs.

### CODE REVIEW

**Comment by ZacLN** [comment]
Reorg looks good but breaks 'change module' and the repl variable tree view

**Comment by davidanthoff** [comment]
I'm on it!

**Comment by davidanthoff** [comment]
I think this should do the trick, both are working for me again. Thanks for being careful and finding this :)

**Comment by ZacLN** [comment]
Yep thats done it

**Comment by ZacLN** [comment]
Can we make the html/svg displayer communicate through the same pipe as the new REPL functions?

**Comment by davidanthoff** [comment]
Yeah, I don't see why not. Maybe a v0.9.0 project?

**Comment by ZacLN** [comment]
Yeah, no rush/end user impact

**Pull request merged**
