### PR TITLE
WIP Add table view option

### PR DESCRIPTION
**Pull request by davidanthoff**
Very much work in progress.

I'm using https://www.datatables.net/ for the actual UI, mostly because it seemed really simple to integrate. Probably worth checking whether that is a good choice or not.

### CODE REVIEW

**Comment by xiaodaigh** [comment]
I had some experience using the https://github.com/bvaughn/react-virtualized to show only part of the table; so it would be an awesome addition as performance can serious degradation if not careful with the implementation especially when dealing with large datasets.

datatables.net is fine if you implementation the lazy load feature. I find react-virtualized easier to use but then you have to use react but I guess it's quite popular now.

**Comment by Ken-B** [comment]
see #176, a reminder from the past ;-)

**Comment by davidanthoff** [comment]
Haha, yes, this is not new. But now I have a bit more of an idea how to do it and actually think it is not really that big of a project. At least to get something basic going. Big datasets will be a different story...

**Comment by davidanthoff** [comment]
I'm closing this attempt because the whole architecture for custom web views in VS Code has changed in the meantime. I still plan to do this, but there is nothing in this PR that would be useful at this point.

**Pull request closed without merging**
