### PR TITLE
change JuliaParser version

### PR DESCRIPTION
**Pull request by ZacLN**
I need this fork of JuliaParser before adding to LS.jl, I'm unsure if this is all that needs to be done to change the version>

### CODE REVIEW

**Comment by davidanthoff** [comment]
I think that should do it... But lets first see whether you can merge your changes into upstream, so that we don't need our own fork.

**Comment by ZacLN** [comment]
I'll give it a shot!... but I don't that'll pass muster, it's a pretty hacky way to piggy back information out (and I have literally no idea what the `.typ` field is supposed to do).

**Comment by be5invis** [comment]
@ZacLN It is simply an improved version of #111, so keep this is fine.

**Comment by davidanthoff** [comment]
> @ZacLN It is simply an improved version of #111, so keep this is fine.

@be5invis Was that comment meant to go to some other issue/PR? I don't understand it in the context here :)

**Comment by be5invis** [comment]
@davidanthoff sorry.

**Comment by ZacLN** [comment]
shall we merge this?

**Pull request merged**
