### PR TITLE
incremental document handling

### PR DESCRIPTION
**Pull request by ZacLN**
@davidanthoff could you see if this works when you get a chance?

This parses documents into blocks, runs the linter on the individual blocks and picks up some information about local variables for functions.

When a didChange event happens it marks blocks intersect with the change and re-parses only those affected...ish. Saving the file parses everything afresh.

The line numbers on diagnostics are a bit wonky

### CODE REVIEW

**Comment by davidanthoff** [comment]
@ZacLN Can you resolve the merge conflict?

**Comment by ZacLN** [comment]
Yep, let me close this

**Comment by davidanthoff** [comment]
There is in general no need to close  PR to resolve a merge conflict. Normally it should be enough that you do the following locally on your machine:

1. make sure you have pulled the latest ``master``
2. checkout your branch (i.e. ``allrange``)
3. merge ``master`` into ``allrange``
4. resolve any merge conflict
5. push ``allrange``

That should normally do the trick. Main benefit is that we don't loose the discussion history here.

**Comment by ZacLN** [comment]
arg, appologies for that

**Comment by davidanthoff** [comment]
No need to apologize, what you are contributing here is just plain amazing!

**Pull request closed without merging**
