### PR TITLE
Update syntax file with nested type parameter group support

### PR DESCRIPTION
**Pull request by be5invis**

### CODE REVIEW

**Comment by ZacLN** [comment]
Looks good, could you add `using` to the keyword group before I merge?

**Comment by be5invis** [comment]
Will do it later

???? iPhone

? 2016?12?1??16:23?ZacNugent <notifications@github.com<mailto:notifications@github.com>> ???


Looks good, could you add using to the keyword group before I merge?

-

**Comment by ZacLN** [comment]
Cheers

**Comment by be5invis** [comment]
@ZacLN `using` is already there, alongside with `import`.

**Comment by ZacLN** [comment]
Sorry, I had a misunderstanding on grammars work, turns out the theme I use is just incomplete

**Pull request merged**
