### PR TITLE
snippets: update struct's snippets and add let/begin block

### PR DESCRIPTION
**Pull request by iblis17**

### CODE REVIEW

**Comment by davidanthoff** [comment]
@ZacLN are you ok with this? I'm holding of to merge until you reviewed this as well.

**Comment by ZacLN** [comment]
Sorry I’m away until Tuesday without WiFi, will go through everything that evening

**Comment by davidanthoff** [comment]
Enjoy the internet free time!

**Comment by davidanthoff** [comment]
Thanks, @iblis17!

**Pull request merged**
