### PR TITLE
snippets: enhance function's snippet

### PR DESCRIPTION
**Pull request by iblis17**
peek 2017-11-09 20-42

### CODE REVIEW

**Comment by davidanthoff** [comment]
I'm not a fan of this, to be honest. I feel it imposes a specific coding style on a large user base that is not really an official julia thing. I think folks that would like this kind of snippet can just add this (or some other favorite style) to their own installation with these instructions: https://code.visualstudio.com/docs/editor/userdefinedsnippets.

**Comment by iblis17** [comment]
I agree that everyone has different coding style.
Can we create a snippet gallery or something like that to collect various contributed snippet?

**Comment by davidanthoff** [comment]
Yes, that is a great idea! Maybe just a wiki page for now?

**Comment by iblis17** [comment]
I added them here: https://github.com/JuliaEditorSupport/julia-vscode/wiki/Snippets#gallery

**Comment by davidanthoff** [comment]
Great, thanks!

**Pull request closed without merging**
