### PR TITLE
WIP Use LanguageServer package

### PR DESCRIPTION
**Pull request by davidanthoff**
Don't merge this! This is work in progress that we can merge once we have released v0.5.0. This uses the LanguageServer package.

I've also changed things so that in debug mode the language server is just using the packages from the system package location, not a private installation. In release mode it is still using its own copy of things. That should make dev for us simpler.

### CODE REVIEW

**Comment by ZacLN** [comment]
Fantastic stuff! So, for development I should push all PR's to LanguageServer and push bug fixes to this and the LanguageServer, right?

**Comment by davidanthoff** [comment]
Yes, exactly. Hopefully we can keep the churn rate on master here low for 0.5.0, and then move onto 0.6.0.

**Comment by ZacLN** [comment]
Also, I think a file restructuring might be nice such that all document handling like didOpen methods and parsing/linting are all in one file. If you agree I'll submit a PR tomororw

**Comment by davidanthoff** [comment]
Yes, that makes sense to do this in the LanguageServer repo, right?

**Comment by ZacLN** [comment]
Yes

**Comment by davidanthoff** [comment]
I've just merged the split directly onto ``master``, mainly because there was some submodule stuff going on that was not super trivial. See #58 for the plan for the 0.5 release.

**Pull request closed without merging**
