### PR TITLE
Add lint-package command

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by ZacLN** [comment]
@davidanthoff , have you had a chance to look at this (and accompanying PRs) yet?

**Comment by davidanthoff** [comment]
Why do we need a command for this? Shouldn't the linter just automatically run in the background and report any problems?

**Comment by ZacLN** [comment]
Ah yeah, I've given no description. 

The idea was to have a special 'package-lint' command that does slightly heavier duty linting checking for publishing requirements (i.e. things listed [here](https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/53))

**Comment by davidanthoff** [comment]
Ah, makes sense!

**Pull request merged**
