### PR TITLE
Add test runner command

### PR DESCRIPTION
**Pull request by davidanthoff**
Implements #100

### CODE REVIEW

**Comment by davidanthoff** [comment]
It is a stop-gate until Microsoft/vscode#15179 is implemented, i.e. native VS Code UI for running tests.

My typical dev cycle is that I edit code, immediately run the unit tests to see whether anything broke, edit code etc. So this makes that a little easier.

**Comment by ZacLN** [comment]
Ah ok

**Comment by ZacLN** [comment]
On a side note, do you know if it's possible to setup the `.vscode` settings for the LanguageServer so that debugging automatically launches julia-vscode package?

**Comment by davidanthoff** [comment]
Don't know, I now always have one window open with the julia-vscode folder and one with the LS, and then I hit F5 in the julia-vscode window, which starts everything as I want.

**Pull request merged**
