### PR TITLE
use bracketed paste to send text to the terminal, fixes indentation problems

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes indentation problems.

I have no idea how to test this. 

Ref: https://discourse.julialang.org/t/vs-code-extension-v0-11-0-beta-release/17541/9

### CODE REVIEW

**Comment by KristofferC** [comment]
Well, did you try it out somehow and see that it works ok? :P

**Comment by davidanthoff** [comment]
Na, I trust you. Plus we are still in the beta phase, so hopefully problems will be reported back once we ship a new beta.

**Comment by davidanthoff** [comment]
Haha, ok, maybe I will check it out locally then :) I had interpreted your comment as "I don't know how to write an automated test".

**Comment by KristofferC** [comment]
No, it is: "I don't know how to get this to stick in my local extension." :)

**Comment by ZacLN** [comment]
Nope I tried this approach before, it won't work (on linux at least)

**Comment by davidanthoff** [comment]
Ok, I'll revert.

**Comment by KristofferC** [comment]
Why would #495 solve this. Also, can someone tell me how to test this. I don't see a reason why it shouldn't work.

**Comment by davidanthoff** [comment]
The goal with #495 is to in general no longer send code to the REPL as a string a la copy-paste, but instead have a background green thread in the REPL process that listens on a named pipe for messages from the extension (we already have that background server), and then code to be executed would be send via this pipe to the REPL process.

**Comment by davidanthoff** [comment]
Easiest way to get a working dev environment for this is to do step 1 & 2 from [Option 3](https://github.com/JuliaEditorSupport/julia-vscode/wiki/Updating-to-the-lastest-julia-vscode#option-3). At that point you can open the julia-vscode folder in VS Code, and run the extension with F5 in a debug environment.

**Comment by KristofferC** [comment]
Okay, FWIW just to make it explicit, this is how things are right now:

nov-15-2018 13-46-02

This keeps going for minutes.

**Pull request merged**
